### ISSUE TITLE
Support Bash highlighting

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/o-syntax-highlight#13]
We end up with a lot of bash in our tutorials and documentation, it'd be good to support bash as a language.

**Comment by rowanmanning** [comment]
I think @lucas42 wants this too?

**Comment by lucas42** [comment]
Yes, that'd be useful.  I rarely do long snippets of bash, just an occasional line for typing in the command line in developer docs.

**Comment by gvonkoss** [comment]
This has been solved! https://github.com/Financial-Times/o-syntax-highlight/pull/14
