### ISSUE TITLE
How to use with Marked

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/o-syntax-highlight#49]
This is not a a bug or a feature request but some information that might be useful to others 🎁 

## What

I am working on a project which uses [Marked](https://www.npmjs.com/package/marked) to convert Markdown files to HTML. Marked supports fenced code blocks but to make the code block output seamlessly integrate with this package some extra class names and attributes must be added to them.

## Details

When using Marked it is possible to override its default renderer so you can create custom output for various elements or features. To get `o-syntax-highlight` compatible output for my code blocks I created a custom renderer to override the default code block:

```js
const marked = require('marked');
const helpers = require('marked/src/helpers');

const renderer = new marked.Renderer();

renderer.code = (code, language, escaped) => {
	const escapedCode = escaped ? code : helpers.escape(code);

	const html = `
		<div data-o-component="o-syntax-highlight">
			<pre><code class="o-syntax-highlight--${language}">${escapedCode}</code></pre>
		</div>
	`;

	return html.trim();
};

marked(content, { renderer });
```

## Additional information

I hope this might be useful for others who need to do the same thing.

**Comment by notlee** [comment]
Thanks! To close this I'm thinking we add a troubleshooting guide to the README with a link here

**Comment by notlee** [comment]
Unless anyone has any other suggestions for a more permanent place for this advice to live?

**Comment by JakeChampion** [comment]
> Thanks! To close this I'm thinking we add a troubleshooting guide to the README with a link here

This ☝️

**Comment by notlee** [comment]
added to the readme 👍
